mynotes/mynotes/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',include('users.urls')),
     path('notes/',include('notes.urls')),
    path('register/',include('users.urls')),

    path('', RedirectView.as_view(url='/login/', permanent=False)),

    #user Login and Logout
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mynotes/notes/urls.py
from django.urls import path
from . import views

app_name = 'notes'

urlpatterns = [
    path('', views.NoteList.as_view(), name='note-list'),
    path('<int:pk>/',views.NoteDetail.as_view(),name='note-detail'),
    path('create/',views.NoteCreate.as_view(),name='note-create'),
    path('<int:pk>/delete/',views.NoteDelete.as_view(),name='note-delete'),
    path('<int:pk>/edit/',views.NoteUpdate.as_view(),name='note-update'),
]

mynotes/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.RegisterView.as_view(), name ='register'),
]

mynotes/notes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Notes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100,null=False)
    body = models.TextField()

    def __str__(self) -> str:
        return self.title
    

mynotes/users/models.py
from django.db import models

# Create your models here.

mynotes/notes/forms.py
from django import forms
from .models import Notes

class NoteForm(forms.ModelForm):
    class Meta:
        model = Notes
        fields = ['title', 'body']

mynotes/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

mynotes/notes/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView,DeleteView,UpdateView
from .forms import NoteForm
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Notes
from django.contrib import messages
from django.urls import reverse_lazy
from django.core.exceptions import PermissionDenied

# Create your views here.

class NoteList(LoginRequiredMixin,ListView):
    model = Notes
    template_name = 'notes/note_list.html'
    context_object_name = 'items'
    paginate_by = 10

    def get_queryset(self) -> QuerySet[Any]:
        context = Notes.objects.filter(user=self.request.user)
        return context
    
class NoteDetail(LoginRequiredMixin,DetailView):
    model = Notes

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.user != self.request.user:
            raise PermissionDenied("You do not have permission to access this note.")
        return obj


class NoteCreate(LoginRequiredMixin,CreateView):
    model = Notes
    form_class = NoteForm
    template_name = 'notes/notes_create.html'
    success_url = reverse_lazy('notes:note-list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, "Note successfully created!")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "There was an error creating the note ! Please correct the errors below.")
        return super().form_invalid(form)

class NoteUpdate(LoginRequiredMixin,UpdateView):
    model = Notes
    form_class = NoteForm
    success_url = reverse_lazy('notes:note-list')

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.user != self.request.user:
            raise PermissionDenied("You do not have permission to update this note.")
        return obj


class NoteDelete(LoginRequiredMixin,DeleteView):
    model = Notes
    success_url = reverse_lazy('notes:note-list')
    context_object_name = 'notes'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.user != self.request.user:
            raise PermissionDenied("You do not have permission to delete this note.")
        return obj

mynotes/users/views.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib import messages



class RegisterView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('login')  # Redirect to login page after registration

    def form_valid(self, form):
        # Optionally, add a success message
        messages.success(self.request, "Your account has been successfully created.")
        return super().form_valid(form)

    def form_invalid(self, form):
        # Optionally, add an error message
        messages.error(self.request, "There was an error with your registration. Please try again.")
        return super().form_invalid(form)

mynotes/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <title>Notes</title>

        <!--CSS File-->
        <link rel="stylesheet" href="{% static 'css/base.css' %}" />
        <script src="https://kit.fontawesome.com/8999b41075.js" crossorigin="anonymous"></script>
        {% block link %} {% endblock %}
    </head>
    <body>
        {% block content %} {% endblock %} 


        
        {% block scripts %}
        {% endblock %}
    </body>
</html>

mynotes/templates/components/header.html
{% extends 'base.html' %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'css/components/header.css' %}" />
{% endblock %} {% block content %}

<header>
        <div class="nav-wrapper">
          <a href="#" class="brand-logo">NOTES</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="{% url 'notes:note-list' %}">Mylist</a></li>
            <form action="{% url 'logout' %}" method="post" style="display: inline;">
              {% csrf_token %}
             <button type="submit" class="logout-button">Logout</button>
            </form>
          </ul>
        </div>
   
</header>

{% endblock %}

mynotes/templates/notes/note_list.html
{% extends 'base.html' %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'css/notes/note_list.css' %}" />
{% endblock %} {% block content %}

{% include 'components/header.html' %}

<section>
    {% if messages %}
    <div class="message-container">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
    {% endif %}
    <div class="sub-header">
        <a href="{% url 'notes:note-create' %}"><button class="add-button" title="Add"><i class="fa-solid fa-plus"></i></button></a>
    </div>
    <div class="content">
        {% for item in items %}
        <a href="{% url 'notes:note-detail' item.id %}">
            <div class="card">
                <span class="subject">Subject:</span>
                <h3>{{ item.title }}</h3>
            </div>
        </a>
        {% endfor %}
    </div>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</section>

{% endblock %}

mynotes/templates/notes/notes_confirm_delete.html
{% extends 'base.html' %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'css/notes/note_delete.css' %}" />
{% endblock %} {% block content %}

{% include 'components/header.html' %}
<section class="delete-notes">
    <div class="form-container">

        <h1>Are you sure you want to delete "{{ notes.title }}"?</h1>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="">Delete</button>
        </form>
        <a href="{% url 'notes:note-list' %}" class=""><button>Cancel</button></a>
    </div>
</section>

{% endblock %}

mynotes/templates/notes/notes_create.html
{% extends 'base.html' %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'css/notes/note_create.css' %}" />
{% endblock %} {% block content %}

{% include 'components/header.html' %}
<section class="add-notes">
    <div class="form-container">
        <h1>Add Note</h1>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Add</button>
        </form>
    </div>
</section>

{% endblock %}

mynotes/templates/notes/notes_detail.html
{% extends 'base.html' %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'css/notes/note_detail.css' %}" />
{% endblock %} {% block content %} {% include 'components/header.html' %}
<section>
    <div class="note-container">
        <div class="">
            <a href="{% url 'notes:note-update' notes.id %}">
                <button class="edit-btn">
                    <i class="fa-solid fa-pen-to-square"></i>
                </button>
            </a>
            <a href="{% url 'notes:note-delete' notes.id %}">
                <button class="delete-btn">
                    <i class="fa-solid fa-trash"></i>
                </button>
            </a>
            
        </div>
        <h1>{{ notes.title }}</h1>
        <p>{{ notes.body }}</p>
    </div>
</section>

{% endblock %}

mynotes/templates/notes/notes_form.html
{% extends 'base.html' %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'css/notes/note_update.css' %}" />
{% endblock %} {% block content %}

{% include 'components/header.html' %}
<section class="add-notes">
    <div class="form-container">
        <h1>Update Note</h1>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Add</button>
        </form>
    </div>
</section>

{% endblock %}

mynotes/templates/users/login.html
{% extends 'base.html' %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'css/users/login.css' %}" />
{% endblock %} {% block content %}

<section class="login">
    <div class="login-container">
        <h2>Login</h2>
        <form action="" method="post">
            {% csrf_token %} {% for field in form %}
            <label for="{{ field.id_for_label }}" class="labels">{{ field.label }}</label><br />
            {{ field }} {% for error in field.errors %}
            <p class="help text-danger">{{ error }}</p>
            {% endfor %}
            {% endfor %}
            <button type="submit">Login</button>
        </form>
        <div><a href="{% url 'users:register' %}">New user ?</a></div>
    </div>
</section>

{% endblock %}

mynotes/templates/users/logout.html
{% extends 'base.html' %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'css/users/logout.css' %}" />
{% endblock %} {% block content %}

<section class="logout">
    <div class="logout-container">
        <h2>Successfully Logged Out</h2>
        <a href="{% url 'login' %}">Login again?</a>
    </div>
</section>

{% endblock %}

mynotes/templates/users/register.html
{% extends 'base.html' %}
{% load static %}

{% block link %}
<link rel="stylesheet" href="{% static 'css/users/register.css' %}" />
{% endblock %}

{% block content %}
<section class="register">
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
    <div class="registration">
        <h2>Register</h2>
        <form method="post" action="">
            {% csrf_token %}
           
            <div class="form-group">
                {{ form.username.label_tag }}
                {{ form.username }}
            </div>
            
            <div class="form-group">
                {{ form.password1.label_tag }}
                {{ form.password1 }}
            </div>
    
            <div class="form-group">
                {{ form.password2.label_tag }}
                {{ form.password2 }}
            </div>
            
            <button type="submit" class="register-button">Register</button>
        </form>
    </div>
</section>

{% endblock %}